// This file was generated by ScenumGenerator.cs. Do not edit!
// Since Unity serializes enums as ints, do not expose this to the editor. This is meant to easily switch scenes by build index in code
public static class Scenum
{
	public const int EmptyScene = 0;
	public const int MenuScene = 1;
	public const int GameScene = 2;
	public const int Arena = 3;
	public const int PlayerUI = 4;
	public const int GameoverScene = 5;
	public const int UpgradeScene = 6;
}
